# Generated by Django 4.0.1 on 2022-05-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imogame', '0002_alter_kids_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
