# Generated by Django 4.0.1 on 2022-05-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imogame', '0004_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='kid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
