# Generated by Django 4.0.1 on 2022-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imogame', '0005_alter_game_kid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='kids',
            name='l1acc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kids',
            name='l2acc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kids',
            name='l3acc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kids',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kids',
            name='training',
            field=models.BooleanField(default=False),
        ),
    ]
