# Generated by Django 4.0.1 on 2022-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imogame', '0007_remove_kids_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='l1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kids',
            name='l2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kids',
            name='l3',
            field=models.BooleanField(default=False),
        ),
    ]
