# Generated by Django 4.0.1 on 2022-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imogame', '0008_kids_l1_kids_l2_kids_l3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('excited', models.CharField(blank=True, max_length=255, null=True)),
                ('fear', models.CharField(blank=True, max_length=255, null=True)),
                ('happy', models.CharField(blank=True, max_length=255, null=True)),
                ('sad', models.CharField(blank=True, max_length=255, null=True)),
                ('stressed', models.CharField(blank=True, max_length=255, null=True)),
                ('angry', models.CharField(blank=True, max_length=255, null=True)),
                ('excitedvid', models.CharField(blank=True, max_length=255, null=True)),
                ('fearvid', models.CharField(blank=True, max_length=255, null=True)),
                ('happyvid', models.CharField(blank=True, max_length=255, null=True)),
                ('sadvid', models.CharField(blank=True, max_length=255, null=True)),
                ('stressedvid', models.CharField(blank=True, max_length=255, null=True)),
                ('angryvid', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
