# Generated by Django 4.0.1 on 2022-05-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imogame', '0009_level1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level1',
            name='angry',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='angryvid',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='excited',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='excitedvid',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='fear',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='fearvid',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='happy',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='happyvid',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='sad',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='sadvid',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='stressed',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='stressedvid',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
    ]
