# Generated by Django 4.0.1 on 2022-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imogame', '0010_alter_level1_angry_alter_level1_angryvid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=255, null=True)),
                ('surprisevid', models.ImageField(default='default.jpg', upload_to='l1_pics')),
                ('fearvid', models.ImageField(default='default.jpg', upload_to='l1_pics')),
                ('happyvid', models.ImageField(default='default.jpg', upload_to='l1_pics')),
                ('sadvid', models.ImageField(default='default.jpg', upload_to='l1_pics')),
                ('neutralvid', models.ImageField(default='default.jpg', upload_to='l1_pics')),
                ('angryvid', models.ImageField(default='default.jpg', upload_to='l1_pics')),
                ('disgustvid', models.ImageField(default='default.jpg', upload_to='l1_pics')),
            ],
        ),
        migrations.RenameField(
            model_name='level1',
            old_name='angryvid',
            new_name='disgust',
        ),
        migrations.RenameField(
            model_name='level1',
            old_name='excited',
            new_name='neutral',
        ),
        migrations.RenameField(
            model_name='level1',
            old_name='excitedvid',
            new_name='surprise',
        ),
        migrations.RemoveField(
            model_name='level1',
            name='fearvid',
        ),
        migrations.RemoveField(
            model_name='level1',
            name='happyvid',
        ),
        migrations.RemoveField(
            model_name='level1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='level1',
            name='sadvid',
        ),
        migrations.RemoveField(
            model_name='level1',
            name='stressed',
        ),
        migrations.RemoveField(
            model_name='level1',
            name='stressedvid',
        ),
    ]
