# Generated by Django 4.0.1 on 2022-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imogame', '0012_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emot', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('string', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='level2',
            name='angryvid',
            field=models.FileField(default='default.jpg', upload_to='l2_vids'),
        ),
        migrations.AlterField(
            model_name='level2',
            name='disgustvid',
            field=models.FileField(default='default.jpg', upload_to='l2_vids'),
        ),
        migrations.AlterField(
            model_name='level2',
            name='fearvid',
            field=models.FileField(default='default.jpg', upload_to='l2_vids'),
        ),
        migrations.AlterField(
            model_name='level2',
            name='happyvid',
            field=models.FileField(default='default.jpg', upload_to='l2_vids'),
        ),
        migrations.AlterField(
            model_name='level2',
            name='neutralvid',
            field=models.FileField(default='default.jpg', upload_to='l2_vids'),
        ),
        migrations.AlterField(
            model_name='level2',
            name='sadvid',
            field=models.FileField(default='default.jpg', upload_to='l2_vids'),
        ),
        migrations.AlterField(
            model_name='level2',
            name='surprisevid',
            field=models.FileField(default='default.jpg', upload_to='l2_vids'),
        ),
    ]
