# Generated by Django 4.0.1 on 2022-05-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imogame', '0013_level3_alter_level2_angryvid_alter_level2_disgustvid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level3',
            name='string',
        ),
        migrations.AlterField(
            model_name='level3',
            name='emot',
            field=models.ImageField(default='default.jpg', upload_to='l1_pics'),
        ),
    ]
